development:
  adapter: postgresql
  database: own_collection_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: own_collection_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: own_collection_production
  pool: 5
  timeout: 5000
